# Generated by Django 5.0.6 on 2024-06-19 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("liquidations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Spending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "liquidation_sent",
                    models.FileField(
                        blank=True, null=True, upload_to="liquidation_sent/"
                    ),
                ),
                (
                    "account_status",
                    models.FileField(
                        blank=True, null=True, upload_to="account_status/"
                    ),
                ),
                (
                    "liquidation_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="liquidation_certificate/"
                    ),
                ),
                (
                    "signed_liquidation_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="signed_liquidation_certificate/",
                    ),
                ),
                (
                    "invoice",
                    models.FileField(blank=True, null=True, upload_to="invoice/"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INVOICED", "Facturado"),
                            ("NOT_INVOICED", "No Facturado"),
                        ],
                        default="NOT_INVOICED",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("FINISHED", "Finalizado"),
                            ("DELETED", "Eliminado"),
                        ],
                        default="PENDING",
                        max_length=100,
                    ),
                ),
                ("totals_match", models.BooleanField(default=True)),
                ("justification", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spendings_registered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidations",
                    models.ManyToManyField(
                        related_name="spendings_registered",
                        to="liquidations.liquidation",
                    ),
                ),
            ],
        ),
    ]
