# Generated by Django 5.0.6 on 2024-06-19 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Liquidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("document_type_code", models.CharField(max_length=75)),
                ("invoice_nit", models.CharField(default="CF", max_length=75)),
                (
                    "invoice_serie",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("invoice_number", models.TextField()),
                ("invoice_name", models.CharField(max_length=100)),
                ("invoice_adress", models.CharField(blank=True, max_length=150)),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                ("document_link", models.TextField(blank=True)),
                (
                    "state",
                    models.PositiveIntegerField(
                        choices=[(1, "Activo"), (2, "Anulado")], default=1
                    ),
                ),
                ("is_devolution", models.BooleanField(default=False)),
                ("elimination_reason", models.CharField(blank=True, max_length=250)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="liquidations/"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
